# PostgreSQL - реляционная СУБД
# Alembic - система миграций для SQLAlchemy
# Настраиваем конфигурацию Alembic

# Селекция (Selection) — это процесс выбора или отбора данных из базы данных
# с помощью SQL-запроса SELECT

# Хранит настройки подключения к БД
[alembic]
sqlalchemy.url = postgresql+asyncpg://ilya:77777@localhost:5433/ActorBD
script_location = alembic  # Указывает расположение скриптов миграций


#Определяет три логгера (регистратора событий), которые будут использоваться Alembic
# root - Захватывает ВСЕ логи приложения,
# если они не перенаправлены в другие логгеры, WARN (только предупреждения и ошибки)
# sqlalchemy - Логирует SQL-запросы, которые генерирует SQLAlchemy, WARN (SQL-запросы не показываются)
# alembic - Логирует действия миграций, INFO (информационные сообщения)
[loggers]
keys = root,sqlalchemy,alembic


# Handlers определяют куда отправлять логи
[handlers]
keys = console # Используем один обработчик: 'console'

#[formatters] — это секция конфигурации, которая определяет "как будут выглядеть логи".
# Это "стилистическое оформление" для сообщений.
[formatters]
keys = generic


#[logger_root] — это конфигурация корневого логгера.
# Это "родительский" логгер, который ловит ВСЁ, что не было перехвачено
# другими логгерами.
[logger_root]
level = WARN # Минимальный уровень: WARNING
handlers = console # Отправлять в консоль
qualname = root # Имя логгера: root


# стенограф SQL-запросов
# Записывает ВСЕ SQL команды, которые отправляются в PostgreSQL
[logger_sqlalchemy]
level = WARN # показывать только предупреждения и ошибки
handlers =   # Наследует обработчики от корневого логгера (root)
qualname = sqlalchemy.engine # Логировать только движок SQLAlchemy
# Не логировать: sqlalchemy.pool, sqlalchemy.orm и т.д.


# диспетчер миграций
#[logger_alembic] — это конфигурация логгера для самого Alembic,
# который отслеживает все операции миграций базы данных.
[logger_alembic]
level = INFO # Минимальный уровень: INFO
handlers =   # наследует от root
qualname = alembic # Логировать весь пакет alembic


# принтер для логов
# [handler_console] — это настройка обработчика,
# который отправляет логи в консоль (терминал).
[handler_console]
class = StreamHandler  # Класс обработчика
args = (sys.stderr,)   # Куда писать
level = NOTSET         # Уровень фильтрации
formatter = generic    # Как форматировать


# шаблон для печати логов
# [formatter_generic] — это настройка форматтера,
# который определяет как выглядят логи в консоли.
# Берет сырые данные (сообщение, уровень, имя логгера)
# Подставляет их в шаблон format
# Добавляет время по формату datefmt
# Возвращает красиво оформленную строку
[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S